version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - laravel

networks:
  laravel:
